#!/bin/bash 

for product in kubic caasp; do
    for file in *kiwi.ini; do
        newfile=$(echo "${file}" | sed "s/^\(.*\).kiwi.ini/${product}-\1.kiwi/")
        cp "${file}" "${newfile}"
        if [ "${product}" == "kubic" ]; then
            baseimage="opensuse/tumbleweed#current"
            distro="openSUSE Kubic"
        else
            baseimage="suse/sles15#current"
            distro="SLES15"
        fi
        sed -i -e "s@_BASEIMAGE_@${baseimage}@g" \
            -e "s/_DISTRO_/${distro}/g" \
            -e "s/_PRODUCT_/${product}/g" \
            -e "/^<image/i\<!--\n\tThis is an autogenerated \
file from ${file} template.\n\tDo not manually modify \
this file.\n-->\n" "${newfile}"
    done
done
